### ISSUE TITLE
无论点击哪一个项后，总是滑动到第0个

### ISSUE THREAD

**Issue by tangxueyun** [ryanlijianchang/Recyclerview-Gallery#13]
GalleryRecyclerView中的
        if (hasWindowFocus) {
            //scrollToPosition(0);
            smoothScrollToPosition(0);
        }
        else {
           scrollToPosition(0);
        }
会导致无论点击哪一个项后，都会滑动到第0个项
建议将以上代码更改为
smoothScrollToPosition(getScrolledPosition());
也可以避免第0项的margin不对

**Comment by ryanlijianchang** [comment]
已fix
