### ISSUE TITLE
调用适配器刷新后，view显示异常

### ISSUE THREAD

**Issue by 199208121113** [ryanlijianchang/Recyclerview-Gallery#17]
调用Adapter.notifyDataSetChanged/notifyItemChanged之后，中间视图异常显示，再次触摸屏幕，触发滑动，视图回归正常

**Comment by ryanlijianchang** [comment]
可以把你代码贴出来吗？

**Comment by 199208121113** [comment]
功能点如下：点击item当中的保存按钮-->成功后文本描述为“已保存”
主界面代码如下：
package com.x.learn;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.view.View;
import com.ryan.rv_gallery.AnimManager;
import com.ryan.rv_gallery.GalleryRecyclerView;
import com.x.core.adapter.NewAdapterItem;
import com.x.core.adapter.NewOnAdapterItemStateChangeListener;

public class MainActivity extends AppCompatActivity implements GalleryRecyclerView.OnItemClickListener{


    GalleryRecyclerView mRecycleView;
    GalleryRecycleAdapter mAdapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mRecycleView = findViewById(R.id.rv_list);
        mAdapter = new GalleryRecycleAdapter(this);
        mRecycleView.setLayoutManager(new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false));
        mRecycleView.setAdapter(mAdapter);

        mRecycleView.initFlingSpeed(5000)                                   // 设置滑动速度（像素/s）
                .initPageParams(0, 60)     // 设置页边距和左右图片的可见宽度，单位dp
                .setAnimFactor(0.15f)                                       // 设置切换动画的参数因子
                .setAnimType(AnimManager.ANIM_BOTTOM_TO_TOP)                // 设置切换动画类型，目前有AnimManager.ANIM_BOTTOM_TO_TOP和目前有AnimManager.ANIM_TOP_TO_BOTTOM
                .setOnItemClickListener(this);                              // 设置点击事件
        loadTestData();
    }

    private void loadTestData() {
        for (int i = 0; i < 10; i++) {
            mAdapter.addItem(new GalleryModel(), null, listener);
        }
        mAdapter.notifyDataSetChanged();
    }

    private NewOnAdapterItemStateChangeListener listener = new NewOnAdapterItemStateChangeListener() {
        @Override
        public void onStateChanged(NewAdapterItem item, View v, int... posIndex) {
            GalleryModel gm = (GalleryModel) item.getData();
            gm.setSave(!gm.isSave());
            mAdapter.notifyItemChanged(posIndex[0]);
        }
    };


    @Override
    public void onItemClick(View view, int i) {

    }
}

listener：对应保存点击事件，  我修改对应状态后刷新item
Adapter当中就是简单的根据状态，赋值按钮文本

**Comment by 199208121113** [comment]
Xml代码：
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.ryan.rv_gallery.GalleryRecyclerView
        android:id="@+id/rv_list"
        android:layout_width="match_parent"
        android:layout_height="480dp"
        app:helper="LinearySnapHelper" />

</android.support.constraint.ConstraintLayout>

**Comment by 199208121113** [comment]
@ryanlijianchang 已解决！ 
问题总结：RecycleView的局部刷新问题！  参考：https://blog.csdn.net/jdsjlzx/article/details/52893469
1、常用需求，如果仅仅是图片展示，item添加完以后不涉及到刷新操作，没有任何问题！ 如果在添加完Item之后，根据用户操作需要刷新Item项，就会出现我上面描述的问题了。
2.解决方式：重写Adapter->onBindViewHolder(VH holder, int position, List<Object> payloads)->notifyItemChanged(int position, Object payload) 刷新对应item即可
部分代码如下：
适配器:
 @Override
    public void onBindViewHolder(MyHolder holder, int position, List<Object> payloads) {
        if(payloads.isEmpty()){
            onBindViewHolder(holder, position);
        }else {
            GalleryModel gm = mDatas.get(position);
            boolean isSave = gm.isSave();
            String desc = isSave ? "已保存" : "保存";
            holder.tvSave.setText(desc);
        }
    }

    @Override
    public void onBindViewHolder(MyHolder holder, int position) {
        boolean isSave = mDatas.get(position).isSave();
        String desc = isSave ? "已保存" : "保存";
        holder.tvSave.setText(desc);
    }

刷新代码：
        gm.setSave(!gm.isSave());
        mAdapter.notifyItemChanged(position, this.getClass().getName());

楼主大大可以看看是否有其他解决方案

**Comment by ryanlijianchang** [comment]
你的做法是正确的，例子可看分支branch_update_item_notify
