### ISSUE TITLE
Fragment 中使用出现异常

### ISSUE THREAD

**Issue by luhaikong** [ryanlijianchang/Recyclerview-Gallery#18]
FragmentA中使用了GalleryRecyclerView，切换到FragmentB，再切换到FragmentA，此时GalleryRecyclerView的缩放和动画等不能正常执行。

**Comment by ryanlijianchang** [comment]
hi，使用最新版本V1.1.0已经解决问题。

分支branch_double_fragment有个demo，你可以看看
