### ISSUE TITLE
GalleryRecyclerView调用smoothScrollToPosition( )偏差

### ISSUE THREAD

**Issue by saveus** [ryanlijianchang/Recyclerview-Gallery#19]
GalleryRecyclerView设置了占满屏幕每次展示一个item
android:layout_width="match_parent"
android:layout_height="match_parent"
并且
.initPageParams(0, 0).setAnimFactor(0f)
这样在使用smoothScrollToPosition( )时会出现位置偏移很多，比如需要滚动的position是4，结果会滚动到13

看了下源码
发现在调用滚动之前加上galleryRecyclerView.onWindowFocusChanged(true);
并且把smoothScrollToPosition( )替换为scrollToPosition( )
就OK了

**Comment by ryanlijianchang** [comment]
V1.1.0版本试试，应该没有这个问题了

**Comment by saveus** [comment]
V1.1.0版本smoothScrollToPosition( )，当定位的真实位置>=5的时候，定位位置会向后偏移1个位置

**Comment by ryanlijianchang** [comment]
你怎么调用的呢？

**Comment by saveus** [comment]
mLayoutManager = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);
galleryView.setLayoutManager(mLayoutManager);
galleryView.smoothScrollToPosition(position);

**Comment by ryanlijianchang** [comment]
更新V1.1.1，提供接口initPosition(int pos)设置默认初始位置，后面可以直接调用smoothScrollToPosition(int pos)移动到需要的位置

**Comment by saveus** [comment]
OK , Thx.
