### ISSUE TITLE
从左向右滑动的时候有几率会出现某张图片已经完全展示，但是却返回到了上一张图片位置的问题。

### ISSUE THREAD

**Issue by tingshuonitiao** [ryanlijianchang/Recyclerview-Gallery#21]
比如: 从左向右滑动的时候，第三张图片已经完全展示，却回到了第二张图片的位置。

在
(1) initPosition()传0
(2) 修改了GalleryRecyclerView的`onItemSizeMeasured(int size)`
的情况下, 不会出现如上bug。

测试的时候, 看了log, 感觉和SnapHelper的`snapToTargetExistingView()`的实现有关。

**Comment by ryanlijianchang** [comment]
把你的修改提个pull request看一下？

**Comment by tingshuonitiao** [comment]
提了
