### ISSUE TITLE
点击item 滚动没反应

### ISSUE THREAD

**Issue by rebertBen** [ryanlijianchang/Recyclerview-Gallery#34]
mRecyclerView.smoothScrollToPosition(position); 方法不起作用

**Comment by ryanlijianchang** [comment]
> mRecyclerView.smoothScrollToPosition(position); 方法不起作用

初始化时可以调用initPosition设置初始化位置，等初始化完成后调用smoothScrollToPosition是没问题的
```
// 设置初始化的位置
mRecyclerView.initPosition(1)
```
