### ISSUE TITLE
重新设置数据显示效果会乱

### ISSUE THREAD

**Issue by LatoAndroidw** [ryanlijianchang/Recyclerview-Gallery#4]
重新setData notify 会出现缩放和距离错乱的情况，另外》》设置页边距和左右图片的可见宽度，页边距就算设置为0也有很大的边距，只有设置为负数才能缩小

**Comment by ryanlijianchang** [comment]
1.目前notify数据时，新的数据源的大小需要大于等于前一个数据源的大小，这样就不会出现错乱问题。所以建议，两次的数据源的大小是一样的（这个问题后续会考虑改进）。
2.设置页边距为0时还有边距是因为两个方面，一是Demo的Item的布局是CardView，它设置的elevation会导致一定的padding，如果你希望没有的话，需要把CardView换成普通的RelativeLayout。二是设置的切换动画是缩小了才慢慢扩大成当前大小，即alpha值是从小于1慢慢最后变成1，所以也会造成一定的padding效果。综上，如果你希望页面距的大小和你设置的参数大小是一样的话，你就需要把CardView去掉，同时设置setAnimFactor(0f)，这样你设置页边距是0时，两个图片的padding就是0了。

**Comment by moxin73** [comment]
期待作者大神改进padding问题，现在空隙确实有点大，设置setAnimFactor(0.15f)，不用cardView，间距只在滑动产生动画时才出现

**Comment by ryanlijianchang** [comment]
initPageParams(int pageMargin, int leftPageVisibleWidth)你这里配置了pageMargin会有间距的呀

**Comment by jiancao** [comment]
同样的问题，刷新数据会出现缩放
