### ISSUE TITLE
按步骤五添加了代码，背景没有渐变效果 

### ISSUE THREAD

**Issue by LovesdDING** [ryanlijianchang/Recyclerview-Gallery#5]

**Comment by ryanlijianchang** [comment]
背景渐变不是这个库里面的功能，因为可配置性太差了，同时影响一定性能， 可以根据自己需要添加，具体可以参考demo源码，或者看下这篇教程：[用RecyclerView做一个小清新的Gallery效果](https://juejin.im/post/5a30fe5a6fb9a045132ab1bf)
