### ISSUE TITLE
如何设置无限轮播。视图可以用view替换imageview吗？

### ISSUE THREAD

**Issue by AmioLee** [ryanlijianchang/Recyclerview-Gallery#6]
thanks!

**Comment by ryanlijianchang** [comment]
不好意思，现在才回你。
第一个问题，设置无限轮播，很简单，就是制造假象无限轮播，将你的RecyclerView的getCount()方法返回个很大的数，例如 2的32次 -1，如果每次拿到当前位置是通过取余的方式拿，这样就保证了你的数组是无限大了。当然，你需要对边界条件进行保护，下面是一段伪代码，用以实现无限轮播：


public class RecyclerAdapter extends RecyclerView.Adapter<RecyclerAdapter.MyHolder> {

    // ...
    
    @Override
    public void onBindViewHolder(MyHolder holder, int position) {
        // 拿数据时是通过取余的方式
        holder.mView.setImageResource(mDatas.get(position % mDatas.size()));
    }

    @Override
    public int getItemCount() {
        if (mDatas == null || mDatas.size() == 0) {
            return 0;
        } else {
            if (mDatas.size() == 1) {
                return 1;
            } else {
                // 返回Int类型最大值
                return Integer.MAX_VALUE;
            }
        }
    }

    public int getResId(int position) {
        // 拿数据时是通过取余的方式
        return mDatas == null ? 0 : mDatas.get(position % mDatas.size());
    }

    // ...

}

第二个问题，View可以替换ImageView，设置可以是一个复杂的ViewGroup，希望能帮到你
